name: Matrix-Chat-Message Trigger
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to trigger workflow from: `fadenb/matrix-chat-message@<THIS VALUE>`'
        required: true


jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Send message via Matrix
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: fadenb/matrix-chat-message
        ref: ${{ github.event.inputs.ref }}
    - name: Send message to test channel
      id: matrix-chat-message
      uses: ./
      with:
        homeserver: 'matrix.org'
        token: ${{ secrets.MATRIX_TOKEN }}
        channel: '!zzRRnyCqBacUDwvyVW:utzutzutz.net'
        message: 'TEST MESSAGE using fadenb/matrix-chat-message@${{ github.event.inputs.ref }}'
