name: Matrix-Chat-Message Test
on:
  workflow_dispatch:
  push:

jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Send message via Matrix
    steps:
    - name: Send message to test channel
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@master
      with:
        homeserver: 'matrix.org'
        token: ${{ secrets.MATRIX_TOKEN }}
        channel: '!zzRRnyCqBacUDwvyVW:utzutzutz.net'
        message: 'This is an example message. It even supports the use of variables like ${{ github.sha }}'
